### PR TITLE
Drag and drop image support

### PR DESCRIPTION
**Pull request by BrandonMathis**
EZ PZ

http://cl.ly/0V3K3a1L1z0Q

### CODE REVIEW

**Comment by olivierlacan** [comment]
@BrandonMathis I'm sitting on this one for a little bit because you're re-adding a dependency I had recently removed (S3) & CarrierWave so I want to think about it a little bit.

This would become a core feature I would have to maintain and depending on S3 bothers me because I think setting up S3 can be difficult. That said if the feature can be automatically disabled if no S3 setup is found, that could work.

You have some weird stuff in `structure.sql` that don't see at all related to this PR, can you remove them? Thanks. :smiley:

**Comment by fusion2004** [comment]
I think uploading images to articles is a fairly important feature for most wiki needs, so I'm very :+1: about this feature.

I had some issues getting it working, these are the changes I made to get it operational:

```
# editor.coffee
# removed the quotes around true
if $('#image_upload').data('value') == true
   $("#article_content").inlineattach(options)

# articles/_form.html.haml
# added the id the coffeescript is expecting
%meta#image_upload{'data-value' => "#{IMAGE_UPLOAD}"}
```

I didn't test it heavily, but it looks like the conditional operation works after these changes.

**Comment by olivierlacan** [comment]
@BrandonMathis I'd like to revive this soon. I can't watch your video anymore. Like I said initially my main concerns are that S3 is not that great of a dependency to have. It's a relatively complex service to set up but as long as the configuration is conditional (and we disable uploads when it's not there) I think we can swing it for now.

**Comment by BrandonMathis** [comment]
Cool. I will bring the branch up to date with upstream :+1:

**Comment by eredi93** [comment]
any update on this?

**Comment by BrandonMathis** [comment]
Out of curiosity, is there still interest from the community in bringing this feature in? If so, I am happy to bring the changed up-to-date with master but if not I will close this PR for now.

**Comment by olivierlacan** [comment]
@BrandonMathis Feel free to close it. I really appreciate your work but I have some slightly different plans for uploading related to #224. Which is also old as hell. 😞

**Pull request closed without merging**
