### PR TITLE
Bump gems and lock mandrill at 0.5 because next major ver is breaking specs'

### PR DESCRIPTION
**Pull request by hashrocketeer**

### CODE REVIEW

**Comment by olivierlacan** [comment]
You're bumping a lot more gems than just `mandrill` here. I suspect you ran `bundle update` with no arguments (after `update`) which is considered a bad practice. 

Make sure you run `bundle update` explicitly with whichever gems you want to update `gem update mandrill` for example.

**Comment by nikkypx** [comment]
Hey Olivier, 

Yeah, sorry, we should have been more clear.  We actually intended on bumping them all of them but kept Mandrill locked because it was breaking specs.  It looked like it was a problem with that gem, we added an issue there, but not positive.

**Comment by fusion2004** [comment]
We've done similar in our fork: https://github.com/IZEA/orientation/blob/master/Gemfile#L28
I think the issue is that mandrill_mailer changed how using templates works in later versions. I haven't looked very far into it.

**Comment by olivierlacan** [comment]
@fusion2004 We work on mandrill_mailer with @renz45 and he did deprecate the `data` method in 1.0.0. https://github.com/renz45/mandrill_mailer/blob/master/CHANGELOG.md#100

That should be an easy change though @nikkypx. 

Also @nikkypx, I don't want single commits that update multiple gem versions because that makes it very hard to pinpoint regressions later on. As much as possible, and even in a single PR, make sure you have a single commit per gem version bump. I'm sorry if that's tedious, but that's not a risk-free change. We have test coverage but there are many things that can go wrong with massive gem upgrades like this, not all of which can be caught by specs.

**Comment by nikkypx** [comment]
Cool, no problem

**Comment by olivierlacan** [comment]
I'll close this. I can fix the mandrill_mailer upgrade.

**Comment by olivierlacan** [comment]
When [this is merged into mandrill_mailer](https://github.com/renz45/mandrill_mailer/pull/98) we can safely upgrade and dump our duplicated custom matchers, shedding a bunch of code. :-)

**Pull request closed without merging**
