### PR TITLE
Docker build

### LINKED ISSUE #116: Docker support
This seems like a great candidate to have an image up on [Docker Hub](https://registry.hub.docker.com).  I would love to just be able to boot the image and check it out!

### PR DESCRIPTION
**Pull request by jefmathiot**
WIP to fix #116:
* created the Dockerfile
* added a `database.docker.yml` template specific to Docker using the [Docker-Compose convention](https://docs.docker.com/compose/env/) for environment variables
* ensure CarrierWave defaults to file storage when S3 credentials are missing

### CODE REVIEW

**Comment by jefmathiot** [comment]
@ShadowBan are you sure? I havent't found it neither in the ruby image neither in the buildpacks one, but I may be :100: % wrong :). If it's already present Python 2.7.8 would do the job (Pygments requires a 2.7.x version).

I wonder whether we should add an nginx container to Compose configuration in `DOCKER.md` to provide the full stack. How do you feel about it?

**Comment by jefmathiot** [comment]
@ShadowBan :+1: for the mention about Gemfiles. Also, I haven't found a convenient way to cache the Bower `RUN`: it is always invalidated because we `ADD` the project's directory.

**Comment by ShadowBan** [comment]
@jefmathiot I am not 100% about the python either but I know if I do the following it is there...

$ sudo docker run -i -t ruby:2.2.0 bash
root@24322ef31bc7:/# python -V
Python 2.7.8

**Comment by jefmathiot** [comment]
@ShadowBan :+1:

**Comment by ShadowBan** [comment]
@jefmathiot everything looks pretty good.  I am at work right now so I will try a build tonight.  The only other thing I could think to do here is to create a user to install all this under (instead of root) for security sake.

**Comment by jefmathiot** [comment]
@ShadowBan Awesome

**Comment by olivierlacan** [comment]
@jefmathiot You should merger master in, I just removed CarrierWave/S3 and imagemagick so that should simplify things a bunch.

**Comment by jefmathiot** [comment]
Thanks @olivierlacan I merged the master in.

A few questions:
* in the [mail initializer](https://github.com/orientation/orientation/blob/master/config/initializers/mail.rb#L11) AFAICT the environment variable used will always have the same value that `ORIENTATION_DOMAIN`, am I correct ? If so we may use `ORIENTATION_DOMAIN` as the sending domain.
* In the example in the [mandrill_mailer README](https://github.com/renz45/mandrill_mailer) the API key is used as the password. [In the mail initializer](https://github.com/orientation/orientation/blob/master/config/initializers/mail.rb#L10) a separate env var is used. Is that by design ?

If applicable, do you want me to push them on the current PR or a new one?

**Comment by olivierlacan** [comment]
@jefmathiot 

- Noticed you had removed the Python dependency in 3b33954. We still have that due to Pygments.rb although I may try to find another solution down the line, I'm not sold on JS-based solutions for now. That said since code isn't necessarily the majority of the text in most Orientation articles I have, it could be okay to load without syntax highlighting and have it appear after DOMContentLoaded.
- I was thinking about `ORIENTATION_DOMAIN` the other day because I don't like it. It feels silly for the environment to not be aware of its own domain but at least on Heroku's side I couldn't find a way to grab the domain from ENV variables. I think it's safe to use `ORIENTATION_DOMAIN` as the sending domain however, yep.
- The API key was [a recent-ish fix to mandrill_mailer](https://github.com/renz45/mandrill_mailer/commit/7e423d6f6d5aaead70b31efddefcdb1f65f9b9c4), so good catch. ;-)

I'll fix these things on master so don't worry about them.

**Comment by ShadowBan** [comment]
@olivierlacan I belive Python loading in the dockerfile was removed because it is included in the ruby:2.2.0 container by default... so no reason to load it again in the dockerfile.

**Comment by jefmathiot** [comment]
@olivierlacan 

* I removed the Python install step from the build because @ShadowBan spotted it's inherited from the base image specified in the `FROM` step. Python is not an issue for people using orientation with Docker, though it is an additional requirement for those who directly install orientation on their system. +1 to find an alternative to Pygments. I've had a pretty good experience with highlight.js.
* I've had the same problem on another app, the only reliable solution I'd found was to extract the host from the HTTP request instead of relying on the environment. As mandrill_mailer seems to require the values to be defined in an initializer, I don't know if it may be considered here.
* Glad it helped :)

I'll wait for these modifications so that I can merge them and test everything works smoothly in Docker.

**Comment by olivierlacan** [comment]
@jefmathiot Any news on this front? I'm talking to @kytrinyx who's trying to set up a standalone instance of Orientation with Docker and apparently running into issues due to Unicorn.

I think it's because the production setup has only been tested on Heroku and there's an non-explicit dependency on the [`Procfile`](https://github.com/orientation/orientation/blob/master/Procfile) to start to server with: 

```ruby
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
```

**Comment by jefmathiot** [comment]
@olivierlacan Oh, sorry, I was waiting for the `ORIENTATION_DOMAIN` requirement to be removed. If that's will finalize the PR, including the `Procfile` fix, probably tomorrow.

**Comment by jefmathiot** [comment]
@olivierlacan starting from scratch, I followed the instructions in the updated `DOCKER.md` file: everything went fine with this new version.

**Comment by kytrinyx** [comment]
If this works I'll beg my peeps to try it again.

**Comment by jefmathiot** [comment]
@kytrinyx I didn't mentioned it in the README because the image will soon be deployed to the Docker Hub: to build the image use the appropriate tag e.g. `docker build -t orientation .`

**Comment by kytrinyx** [comment]
Thanks @jefmathiot!

**Comment by jefmathiot** [comment]
@kytrinyx :)

**Comment by olivierlacan** [comment]
@jefmathiot I'm going to merge this since [it apparently works](https://twitter.com/DavidHuie/status/628995116884070400). Feel free to submit additional PRs if there was something missing. :-)

**Comment by jefmathiot** [comment]
Thanks @olivierlacan. I'll build the image from the master and push it to the Docker Hub :+1:

**Comment by olivierlacan** [comment]
@jefmathiot You're the best. Thanks! :smile:

**Comment by jefmathiot** [comment]
@olivierlacan it seems I don't have the rights to create a repository on the Docker Hub / orientation organization. I planned to create an Automated Build so that a build is triggered at each commit on the master branch. See here for more https://docs.docker.com/docker-hub/builds/

**Comment by olivierlacan** [comment]
@jefmathiot Should be all set but you should check the build settings, I'm not really sure how it's detecting the `Dockerfile`. Seems like Location: `/` was the right thing to do, but it's not obvious.

https://registry.hub.docker.com/u/orientation/orientation/

**Pull request merged**
