### PR TITLE
Adds Emoji support

### PR DESCRIPTION
**Pull request by BrandonMathis**
:rotating_light: :rotating_light: :rotating_light::rotating_light: :rotating_light::rotating_light: :rotating_light::rotating_light: :rotating_light: You can now add emojis to articles :rotating_light: :rotating_light::rotating_light: :rotating_light::rotating_light: :rotating_light::rotating_light: :rotating_light: :rotating_light: :rotating_light:

### CODE REVIEW

**Comment by olivierlacan** [comment]
Damn. Now I want emoji support on slugs.

**Comment by olivierlacan** [comment]
I can't merge this one. Can you try to rebase master. There might be a conflict with your other PR I just merged.

**Comment by BrandonMathis** [comment]
@olivierlacan should work now :+1:

**Comment by olivierlacan** [comment]
@BrandonMathis Damn I sucked with this, do you mind merging master again and I promise I won't wait 4 months to wake up.

**Comment by BrandonMathis** [comment]
No prob. Should be good now

**Comment by olivierlacan** [comment]
😀😁😃😄😅😆😇😈👿😉😊😋😌😍😎😏😐😑😒😓😔😕😖😗😘😙😚😜😛😝😞😟😠😡😢😣😤😥😦😧😨😩😪😫😬😭😮😯😰😱😲😳😴😵😶😷

**Comment by sarkis** [comment]
Thank you for adding emoji support, however, with the current implementation, this is converting anything that matches emojis, including inside codeblocks. I've proposed a PR that alters the regex to only convert emojis that are not within backticks: 
https://github.com/orientation/orientation/pull/213. @olivierlacan would this be a feature you'd be willing to adopt/merge in? I assumed this was a bug as currently we are getting this in our code blocks:

https://www.dropbox.com/s/vhgp5vzw2oa62cs/Screenshot%202016-01-11%2000.45.40.png?dl=0

**Comment by olivierlacan** [comment]
@sarkis Do you think I should revert this feature?

**Comment by sarkis** [comment]
@olivierlacan I would recommend reverting until we can figure out how to not have text in code blocks be evaluated. I took a stab at this, however, my solution ended up failing for the situations where nested code blocks (3 `) can span multiple lines. The other suggestion I have is doing the emoji conversion in a [redcarpet renderer](https://github.com/vmg/redcarpet#and-you-can-even-cook-your-own) where we can safely only apply to everything except code blocks or anywhere there should be no formatting.

**Pull request merged**
